# Navigation Links
main:
  - name: Bio
    url: /
    weight: 10
  - name: Portfolio
    url: /portfolio/
    weight: 20
  - name: Capstone Projects
    url: /projects/
    weight: 30
  - name: MHA Capstone
    url: /projects/mha-capstone/
    weight: 31
    parent: Capstone Projects
  - name: MPH Capstone
    url: /projects/mph-capstone/
    weight: 32
    parent: Capstone Projects
  - name: Experience
    url: /experience/
    weight: 50
  - name: News
    url: /news/
    weight: 40
  - name: Contact
    url: /contact/
    weight: 60
    main:
  
